module.exports = {
	"light": {
		"a": "",
		"b": "",
		"c": "",
		"d": "",
		"eco": "",
		"easy": "",
		"full": "",
		"save": "",
		"sleep": "",
		"security": "",
		"off": "",
	},
	
	"tv": {
		"power": "",
		"input": "",
		"broadcast": "",
		"volup": "",
		"voldown": "",
		"up": "",
		"down": "",
		"right": "",
		"left": "",
		"decision": "",
		"back": "",
		"menu": "",
		"schedule": "",
		"d": "",
		"blue": "",
		"red": "",
		"green": "",
		"yellow": "",
		"1": "",
		"2": "",
		"3": "",
		"4": "",
		"5": "",
		"6": "",
		"7": "",
		"8": "",
		"9": "",
		"10": "",
		"11": "",
		"12": "",
	},
	
	"aircon": {
		"auto": "",
		"off": "",
		"cool": "",
		"heat": "",
		"dry": "",
		"humidify": "",
		"temp-up": "",
		"temp-down": "",
		"humidify-up": "",
		"humidify-down": "",
		"circulation": "",
		"off-timer": "",
		"sensor": "",
		"speed": "",
		"direction": "",
		"direction": "",
		"filter-clean": "",
		"internal-clean": "",
		"powerful": "",
		"fan": "",
		"sleep": "",
	},
	
	"projector": {
		"ok": "",
		"menu": "",
		"up": "",
		"down": "",
		"right": "",
		"left": "",
	},
	
}
